name: Docker Scout CVE Scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Public images (sample: nginx:1.27)"
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Docker login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}

      - name: Run Docker Scout CVEs
        id: scout
        uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1
        with:
          command: cves
          image: ${{ inputs.image }}
          only-severities: critical,high
          only-fixed: false
          exit-code: true
          sarif-file: scout-results.sarif
      - uses: austenstone/job-summary@67b7e1f68ee55e44d073ab7354e7b580cd09567c # v2.0
        if: always()
        id: summary
        with:
          create-html: false

      - name: Send email with report
        if: always()
        uses: dawidd6/action-send-mail@6d98ae34d733f9a723a9e04e94f2f24ba05e1402 # v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: GitHub Actions
          to: boris.lavrishchev.qubership@gmail.com
          subject: Workflow Report
          #body: ${{ steps.summary.outputs.job-summary-html }}
          html_body: ${{ steps.summary.outputs.job-summary }}
          convert_markdown: true
