name: Docker Scout CVE Scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Public images (sample: nginx:1.27)"
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}

      - name: Run Docker Scout CVEs
        id: scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ inputs.image }}
          only-severities: critical,high
          only-fixed: false
          exit-code: true
          sarif-file: scout-results.sarif
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: boris.lavrishchev.qubership@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://${GITHUB_STEP_SUMMARY}
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
